import os
INTENTS_RAW_PATH=os.environ.get("INTENTS_RAW_PATH")
INTENTS_PROCESSED_PATH=os.environ.get("INTENTS_PROCESSED_PATH")
INTENTS_JSONL_PATH=os.environ.get("INTENTS_JSONL_PATH")
YOUTUBE_CONVERSATIONS_RAW_PATH=os.environ.get("YOUTUBE_CONVERSATIONS_RAW_PATH")
YOUTUBE_CONVERSATIONS_PROCESSED_PATH=os.environ.get("YOUTUBE_CONVERSATIONS_PROCESSED_PATH")
YOUTUBE_CONVERSATIONS_JSONL_PATH=os.environ.get("YOUTUBE_CONVERSATIONS_JSONL_PATH")
FULL_PROCESSED_PATH=os.environ.get("FULL_PROCESSED_PATH")
FULL_JSONL_PATH=os.environ.get("FULL_JSONL_PATH")
